language: python

python:
  - 3.4
  - 3.3
  - 2.7
  - 2.6

sudo: false

env:
  matrix:
    - DJANGO=1.6.11
    - DJANGO=1.7.8
    - DJANGO=1.8.1

install:
  - pip install Django==$DJANGO pytest pytest-django requests responses

script:
  python setup.py test

matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7.8
    - python: 2.6
      env: DJANGO=1.8.1
    - python: 3.3
      env: DJANGO=1.6.11
    - python: 3.4
      env: DJANGO=1.6.11